/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Archivos.Archivo;
import Control.AdmCompra;
import Control.AdmVehiculos;
import Modelo.Vehiculo;
import static Visual.frmConsultarCompras.fecha;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
Grupo #4
Integrantes:
*  Ivonne Roxana Minchala Plúas 
 * Joseph Gabriel García Camacho 
 * Marcos Adonis Merchan Mendoza 
 * Alexander Jesús Zambrano Narváez
 */
public class frmGanancias extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    AdmCompra admVehiculos = new AdmCompra();
    
    DefaultTableModel t = new DefaultTableModel();
    Archivo x = new Archivo();
    
    public void tblGanancias() {
        t.addColumn("CHASIS");
        t.addColumn("MARCA");
        t.addColumn("MODELO");
        t.addColumn("COLOR");
        t.addColumn("AÑO");
        t.addColumn("PRECIO");
        //t.addColumn("FECHA DE COMPRA");
        t.addColumn("MODO DE PAGO");
        t.addColumn("PRECIO FINAL");
        t.addColumn("CUOTA");
        t.addColumn("FECHA");//pendiente
        ingresar();
    }
    
    public void ingresar() {
        String linea, vector[];
        int fila = 0;
        String precios = null;
        double precio = 0;
        try {
            FileReader leer = new FileReader("vehiculos.txt");
            BufferedReader adquirir = new BufferedReader(leer);
            linea = adquirir.readLine();
            while (linea != null) {
                vector = linea.split("#");
                t.addRow(vector);//pendiente
                precio += Double.parseDouble(vector[7]);
                ++fila;
                linea = adquirir.readLine();
            }
            precios = String.format("%.3f", precio);
            t.addRow(new Object[1]);
            t.setValueAt("PRECIO TOTAL", fila, 0);
            t.setValueAt(precios, fila, 7);
            //lblTotal.setText(precios);
        } catch (FileNotFoundException ex) {
            System.err.println("ERROR AL LEER EL ARCHIVO");
        } catch (IOException ex) {
            System.err.println("ERROR AL LEER EL ARCHIVO");
        }
    }

    /**
     * Creates new form frmGanancias
     */
    public frmGanancias(java.awt.Frame parent, boolean modal) {
        this.setContentPane(fondo);
        tblGanancias();
        initComponents();
        this.setTitle("Ganancias");
        //llenarTabla(tblVehiculo,LTotal);
    }
    
    private void llenarTabla(JTable tblGanancias, ArrayList<Vehiculo> lista) {
        /*int fila = 0;
        double precio=0;
        DefaultTableModel venta = (DefaultTableModel) tblGanancias.getModel();
        venta.setNumRows(0);
        if (!lista.isEmpty()) {
            for (Vehiculo v : lista) {
                venta.addRow(new Object[1]);
                tblGanancias.setValueAt(v.getMarca(), fila, 0);
                tblGanancias.setValueAt(v.getModelo(), fila, 1);
                tblGanancias.setValueAt(v.getColor(), fila, 2);
                tblGanancias.setValueAt(v.getAnio(), fila, 3);
                tblGanancias.setValueAt(v.getPrecio(), fila, 4);
                //tblGanancias.setValueAt(v.getCliente(), fila, 4);//no sirve
                tblGanancias.setValueAt(v.getFechaCompra(), fila, 5);
                tblGanancias.setValueAt(v.getModoPago(), fila, 6);
                tblGanancias.setValueAt(v.getPrecioFinal(), fila, 7); 
                precio+=Double.parseDouble(v.getPrecioFinal());
                fila++;
            }
            tblGanancias.setValueAt("PRECIO TOTAL", fila+1, 0); 
            tblGanancias.setValueAt(precio, fila+1, 7); 
            //LTotal.setText(" "); // con set y fila o size();
        }*/
    }
    
    public void llenarTabla() {
        llenarTabla(tblVehiculo, admVehiculos.getListadoCompras());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblVehiculo.setModel(t);
        jScrollPane2.setViewportView(tblVehiculo);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Ganancias General");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/logoCompra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVehiculo;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Picture/M1.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g);
        }
    }
    
}
