/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Archivos.Archivo;
import javax.swing.JOptionPane;
import Control.AdmCompra;
import Modelo.Vehiculo;
import static Visual.frmConsultarCompras.xx;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
Grupo #4
Integrantes:
*  Ivonne Roxana Minchala Plúas 
 * Joseph Gabriel García Camacho 
 * Marcos Adonis Merchan Mendoza 
 * Alexander Jesús Zambrano Narváez
*/
public class frmRealizarCompra extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    frmConsultarCompras obj=new frmConsultarCompras();
    AdmCompra adm = AdmCompra.getAdmCompra();
    Archivo x=new Archivo(); 
    String dia,mes , year;
    String modelo,marca,color,anio,precioP,modoPago,precioFinal,cuota;
    Calendar c=Calendar.getInstance();
    public frmRealizarCompra(java.awt.Frame parent, boolean modal) {
        this.setContentPane(fondo);
        initComponents();
        GpButtons.add(btnCamaro);
        GpButtons.add(btnSail);
        GpButtons.add(btnVenue);
        GpButtons.add(btnElantra);
        GpButtons.add(btnRush);
        GpButtons.add(btnCorolla);

        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtIva.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);

    }
    public void modelo()
    {
        if(btnCamaro.isSelected())
        {
            modelo="CAMARO";
            marca="CHEVROLET";
            color="ROJO";
            anio="2019";
            precioP=txtPrecio.getText();
            precioFinal=txtPrecioFinal.getText();
            cuota=txtCuotas.getText();
        }else if (btnSail.isSelected())
                {
                    modelo="SAIL";
                    marca="CHEVROLET";
                    color="PLATEADO";
                    anio="2020";
                    precioP=txtPrecio.getText();
                    precioFinal=txtPrecioFinal.getText();
                    cuota=txtCuotas.getText();
                }else if (btnVenue.isSelected())
                        {
                           modelo="VENUE"; 
                           marca="HYUNDAI";
                           color="AZUL MARINO";
                           anio="2020";
                           precioP=txtPrecio.getText();
                           precioFinal=txtPrecioFinal.getText();
                           cuota=txtCuotas.getText();
                        }else if (btnElantra.isSelected())
                {
                    modelo="ELANTRA";
                    marca="HYUNDAI";
                    color="BLANCO";
                    anio="2020";
                    precioP=txtPrecio.getText();
                    precioFinal=txtPrecioFinal.getText();
                    cuota=txtCuotas.getText();
                }else if (btnRush.isSelected())
                {
                    modelo="RUSH";
                    marca="TOYOTA";
                    color="VINO";
                    anio="2019";
                    precioP=txtPrecio.getText();
                    precioFinal=txtPrecioFinal.getText();
                    cuota=txtCuotas.getText();
                }else if (btnCorolla.isSelected())
                {
                    modelo="COROLLA";
                    marca="TOYOTA";
                    color="TURQUESA";
                    anio="2020";
                    precioP=txtPrecio.getText();
                    precioFinal=txtPrecioFinal.getText();
                    cuota=txtCuotas.getText();
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GpButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnContado = new javax.swing.JButton();
        btnAgg = new javax.swing.JButton();
        btnCredito = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        btnCamaro = new javax.swing.JRadioButton();
        btnSail = new javax.swing.JRadioButton();
        btnVenue = new javax.swing.JRadioButton();
        btnElantra = new javax.swing.JRadioButton();
        btnRush = new javax.swing.JRadioButton();
        btnCorolla = new javax.swing.JRadioButton();
        btnChevrolet = new javax.swing.JButton();
        btnHyundai = new javax.swing.JButton();
        btnToyota = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioFinal = new javax.swing.JTextField();
        txtPrecioCredito = new javax.swing.JTextField();
        txtCuotas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 550));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Cuotas:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("N.Tarjeta de Credito:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("4 Digitos:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Modo de Pago:");

        txtTarjeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarjetaKeyTyped(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar Compra");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtClave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Precio Final:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Precio:");

        btnContado.setBackground(new java.awt.Color(255, 255, 255));
        btnContado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContado.setText("Contado");
        btnContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContadoActionPerformed(evt);
            }
        });

        btnAgg.setBackground(new java.awt.Color(255, 255, 255));
        btnAgg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgg.setText("Agregar Tarjeta");
        btnAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggActionPerformed(evt);
            }
        });

        btnCredito.setBackground(new java.awt.Color(255, 255, 255));
        btnCredito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCredito.setText("Credito");
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("+Iva %12");

        txtPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        txtIva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });

        btnCamaro.setBackground(new java.awt.Color(255, 255, 255));
        GpButtons.add(btnCamaro);
        btnCamaro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCamaro.setText("Camaro");
        btnCamaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamaroActionPerformed(evt);
            }
        });

        btnSail.setBackground(new java.awt.Color(255, 255, 255));
        GpButtons.add(btnSail);
        btnSail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSail.setText("Sail");
        btnSail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSailActionPerformed(evt);
            }
        });

        btnVenue.setBackground(new java.awt.Color(255, 255, 255));
        GpButtons.add(btnVenue);
        btnVenue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVenue.setText("Venue");
        btnVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenueActionPerformed(evt);
            }
        });

        btnElantra.setBackground(new java.awt.Color(255, 255, 255));
        GpButtons.add(btnElantra);
        btnElantra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnElantra.setText("Elantra");
        btnElantra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElantraActionPerformed(evt);
            }
        });

        btnRush.setBackground(new java.awt.Color(255, 255, 255));
        GpButtons.add(btnRush);
        btnRush.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRush.setText("Rush");
        btnRush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRushActionPerformed(evt);
            }
        });

        btnCorolla.setBackground(new java.awt.Color(255, 255, 255));
        GpButtons.add(btnCorolla);
        btnCorolla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCorolla.setText("Corolla");
        btnCorolla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorollaActionPerformed(evt);
            }
        });

        btnChevrolet.setBackground(new java.awt.Color(255, 255, 255));
        btnChevrolet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChevrolet.setText("Chevrolet");
        btnChevrolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChevroletActionPerformed(evt);
            }
        });

        btnHyundai.setBackground(new java.awt.Color(255, 255, 255));
        btnHyundai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHyundai.setText("Hyundai");
        btnHyundai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHyundaiActionPerformed(evt);
            }
        });

        btnToyota.setBackground(new java.awt.Color(255, 255, 255));
        btnToyota.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnToyota.setText("Toyota");
        btnToyota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToyotaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Elija su Vehiculo");

        txtPrecioFinal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtPrecioCredito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtCuotas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/logoCompra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel10))
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnContado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCuotas)
                            .addComponent(txtPrecioCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtClave)
                            .addComponent(btnCredito)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(171, 171, 171)))))
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCamaro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnChevrolet)
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVenue)
                                            .addComponent(btnElantra)
                                            .addComponent(btnHyundai)))
                                    .addComponent(btnSail))
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRush)
                                    .addComponent(btnToyota)
                                    .addComponent(btnCorolla)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChevrolet)
                            .addComponent(btnHyundai)
                            .addComponent(btnToyota)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCamaro)
                    .addComponent(btnVenue)
                    .addComponent(btnRush))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSail)
                    .addComponent(btnElantra)
                    .addComponent(btnCorolla))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCredito)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContado)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgg))
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCamaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamaroActionPerformed
        JOptionPane.showMessageDialog(null, "Modelo: Camaro\n Color: Rojo\n Año: 2019");
        String modelo = btnCamaro.getText();


        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);

        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        txtIva.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);
        String precio = adm.BuscarModelo(modelo);
        txtPrecio.setText(precio);
        if (precio.equals("123")) {
            
           
            txtPrecio.setText(modelo);
            
             txtIva.setEnabled(false);
            txtPrecioFinal.setEnabled(false);
            txtTarjeta.setEnabled(false);
            txtClave.setEnabled(false);
            txtPrecioCredito.setEnabled(false);
            txtCuotas.setEnabled(false);
        }
            btnChevrolet.setEnabled(false);
            btnHyundai.setEnabled(false);
            btnToyota.setEnabled(false);
            btnCamaro.setEnabled(false);
            //dtcCompra.setEnabled(true);
            btnContado.setEnabled(true);
            btnCredito.setEnabled(true);
    }//GEN-LAST:event_btnCamaroActionPerformed

    private void btnSailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSailActionPerformed
        JOptionPane.showMessageDialog(null, "Modelo: Sail\n Color: Plateado\n Año: 2020");
        String modelo = btnSail.getText();

        btnCamaro.setEnabled(false);

        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        txtIva.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        txtIva.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);
        txtPrecio.setText(adm.BuscarModelo(modelo));
        if (adm.BuscarModelo(modelo).equals("")) { //metodo
            
            
            
            txtPrecioFinal.setEnabled(false);
            txtIva.setEnabled(false);
            txtTarjeta.setEnabled(false);
            txtClave.setEnabled(false);
            txtPrecioCredito.setEnabled(false);
            txtCuotas.setEnabled(false);
        }
            btnChevrolet.setEnabled(false);
            btnHyundai.setEnabled(false);
            btnToyota.setEnabled(false);    
            btnSail.setEnabled(false);
            btnContado.setEnabled(true);
            btnCredito.setEnabled(true);
            //dtcCompra.setEnabled(true);
    }//GEN-LAST:event_btnSailActionPerformed

    private void btnVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenueActionPerformed
        JOptionPane.showMessageDialog(null, "Modelo: Venue\n Color: Azul Marino\n Año: 2021");
        String modelo = btnVenue.getText();

        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);

        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        txtIva.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);
        txtPrecio.setText(adm.BuscarModelo(modelo));
        if (adm.BuscarModelo(modelo).equals("")) { //metodo
           
            txtPrecioFinal.setEnabled(false);
            txtTarjeta.setEnabled(false);
            txtClave.setEnabled(false);
            txtPrecioCredito.setEnabled(false);
            txtCuotas.setEnabled(false);
        }
            btnChevrolet.setEnabled(false);
            btnHyundai.setEnabled(false);
            btnToyota.setEnabled(false);
            btnVenue.setEnabled(false);
            //dtcCompra.setEnabled(true);
            btnContado.setEnabled(true);
            btnCredito.setEnabled(true);
    }//GEN-LAST:event_btnVenueActionPerformed

    private void btnElantraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElantraActionPerformed
        JOptionPane.showMessageDialog(null, "Modelo: Elantra\n Color: Blanco\n Año: 2020");
        String modelo = btnElantra.getText();

        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);

        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);
        txtPrecio.setText(adm.BuscarModelo(modelo));
        if (adm.BuscarModelo(modelo).equals("")) { //metodo
           
            txtPrecioFinal.setEnabled(false);
            txtTarjeta.setEnabled(false);
            txtClave.setEnabled(false);
            txtPrecioCredito.setEnabled(false);
            txtCuotas.setEnabled(false);
        }
            btnChevrolet.setEnabled(false);
            btnHyundai.setEnabled(false);
            btnToyota.setEnabled(false);
            btnElantra.setEnabled(false);
            btnContado.setEnabled(true);
            btnCredito.setEnabled(true);
            //dtcCompra.setEnabled(true);
    }//GEN-LAST:event_btnElantraActionPerformed

    private void btnRushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRushActionPerformed
        JOptionPane.showMessageDialog(null, "Modelo: Rush\n Color: Vino\n Año: 2019");
        String modelo = btnRush.getText();
        JOptionPane.showMessageDialog(null, modelo);

        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);

        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);
        txtPrecio.setText(adm.BuscarModelo(modelo));
        if (adm.BuscarModelo(modelo).equals("")) { //metodo
            
            txtPrecioFinal.setEnabled(false);
            txtTarjeta.setEnabled(false);
            txtClave.setEnabled(false);
            txtPrecioCredito.setEnabled(false);
            txtCuotas.setEnabled(false);
        }
            btnChevrolet.setEnabled(false);
            btnHyundai.setEnabled(false);
            btnToyota.setEnabled(false);
            btnRush.setEnabled(false);
            btnContado.setEnabled(true);
            btnCredito.setEnabled(true);
            //dtcCompra.setEnabled(true);
    }//GEN-LAST:event_btnRushActionPerformed

    private void btnCorollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorollaActionPerformed
        JOptionPane.showMessageDialog(null, "Modelo: Corolla\n Color: Turquesa\n Año: 2021");
        String modelo = btnCorolla.getText();
        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);

        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(false);
        txtPrecio.setText(adm.BuscarModelo(modelo));
        if (adm.BuscarModelo(modelo).equals("")) { //metodo
            
            txtPrecioFinal.setEnabled(false);
            txtTarjeta.setEnabled(false);
            txtClave.setEnabled(false);
            txtPrecioCredito.setEnabled(false);
            txtCuotas.setEnabled(false);
        }
            btnChevrolet.setEnabled(false);
            btnHyundai.setEnabled(false);
            btnToyota.setEnabled(false); 
            btnCorolla.setEnabled(false);
            btnContado.setEnabled(true);
            btnCredito.setEnabled(true);
            //dtcCompra.setEnabled(true);
    }//GEN-LAST:event_btnCorollaActionPerformed

    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed
        modoPago="CREDITO";
        String modelo = txtPrecio.getText();
         String Cuota=txtPrecio.getText();
        btnChevrolet.setEnabled(false);
        btnHyundai.setEnabled(false);
        btnChevrolet.setEnabled(false);
        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
      //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
         txtPrecioCredito.setText(adm.BuscarCredito(modelo));
         txtPrecioFinal.setText(adm.BuscarCredito(modelo));
         txtCuotas.setText(adm.BuscarCuota(Cuota));
         if (adm.BuscarCuota(Cuota).equals(""))
         if (adm.BuscarCredito(modelo).equals("")) {
          
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(true);
        txtClave.setEnabled(true);
        txtPrecioCredito.setEnabled(true);
        txtCuotas.setEnabled(true);
          
        }
        txtTarjeta.setEnabled(true);
        txtClave.setEnabled(true);
        btnAgg.setEnabled(true);
        btnAceptar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditoActionPerformed

    private void btnChevroletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChevroletActionPerformed

        btnCamaro.setEnabled(true);
        btnSail.setEnabled(true);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAceptar.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnChevroletActionPerformed

    private void btnHyundaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHyundaiActionPerformed

        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(true);
        btnElantra.setEnabled(true);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAceptar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHyundaiActionPerformed

    private void btnToyotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToyotaActionPerformed

        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(true);
        btnCorolla.setEnabled(true);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        btnAceptar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToyotaActionPerformed

    private void btnContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContadoActionPerformed
        txtCuotas.setText("0");
        modoPago="CONTADO";
        String modelo = txtPrecio.getText();
        btnChevrolet.setEnabled(false);
        btnHyundai.setEnabled(false);
        btnChevrolet.setEnabled(false);
        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setText(adm.BuscarContado(modelo));
        txtIva.setText(adm.BuscarIva(modelo));
        if (adm.BuscarContado(modelo).equals("")) {
        txtPrecioFinal.setEnabled(true);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        }
        btnAceptar.setEnabled(true);
    }//GEN-LAST:event_btnContadoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        modelo();
        dia=String.valueOf(c.get(Calendar.DAY_OF_MONTH));
        mes=String.valueOf(c.get(Calendar.MONTH)+1);
        year=String.valueOf(c.get(Calendar.YEAR));
        obj.fecha=dia+"/"+mes+"/"+year;
        String chevrolet=btnChevrolet.getText();
         String hyundai=btnHyundai.getText();
         String toyota=btnToyota.getText();
         String camaro=btnCamaro.getText();
         String sail=btnSail.getText();
         String venue=btnVenue.getText();
         String elantra=btnElantra.getText();
         String rush=btnRush.getText();
         String corolla=btnCorolla.getText();
         String precio=txtPrecio.getText();
         //Date fecha=dtcCompra.getDate();
         String contado=btnContado.getText();
         String precioIva=txtPrecioFinal.getText();
         String credito=btnCredito.getText();
         String precioCredito=txtPrecioCredito.getText();
         String cuotas=txtCuotas.getText();
         String tarjeta=txtTarjeta.getText();
         String clave=txtClave.getText();
         int numchasis=(int)(Math.random()*100);
         x.añadir(String.valueOf(numchasis),marca, modelo, color, anio, precioP, modoPago, precioFinal, cuota);
         xx.add(new Vehiculo(String.valueOf(numchasis),marca, modelo, color, anio, precioP, modoPago, precioFinal, cuota));
       x.llenar(dia+"/"+mes+"/"+year);
       x.vaciarArreglo();
       JOptionPane.showMessageDialog(null, "Compra Guardada ");
        btnChevrolet.setEnabled(false);
        btnHyundai.setEnabled(false);
        btnToyota.setEnabled(false);
        btnCamaro.setEnabled(false);
        btnSail.setEnabled(false);
        btnVenue.setEnabled(false);
        btnElantra.setEnabled(false);
        btnRush.setEnabled(false);
        btnCorolla.setEnabled(false);
        txtPrecio.setEnabled(false);
        //dtcCompra.setEnabled(false);
        btnContado.setEnabled(false);
        btnCredito.setEnabled(false);
        txtPrecioFinal.setEnabled(false);
        txtPrecioCredito.setEnabled(false);
        txtCuotas.setEnabled(false);
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);  
        btnAceptar.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed

    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggActionPerformed
        
        txtTarjeta.setEnabled(false);
        txtClave.setEnabled(false);
        btnAgg.setEnabled(false);
        btnAceptar.setEnabled(true);
    }//GEN-LAST:event_btnAggActionPerformed

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();

        if ((c < '0' || c > '9') || (txtClave.getText().trim().length() >= 4)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtClaveKeyTyped

    private void txtTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarjetaKeyTyped

        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') || (txtTarjeta.getText().trim().length() >= 16)) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaKeyTyped

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GpButtons;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgg;
    private javax.swing.JRadioButton btnCamaro;
    private javax.swing.JButton btnChevrolet;
    private javax.swing.JButton btnContado;
    private javax.swing.JRadioButton btnCorolla;
    private javax.swing.JButton btnCredito;
    private javax.swing.JRadioButton btnElantra;
    private javax.swing.JButton btnHyundai;
    private javax.swing.JRadioButton btnRush;
    private javax.swing.JRadioButton btnSail;
    private javax.swing.JButton btnToyota;
    private javax.swing.JRadioButton btnVenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCuotas;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioCredito;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Picture/M1.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
}
