/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Archivos.Archivo;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/*
Grupo #4
Integrantes:
*  Ivonne Roxana Minchala Plúas 
 * Joseph Gabriel García Camacho 
 * Marcos Adonis Merchan Mendoza 
 * Alexander Jesús Zambrano Narváez
*/
public class frmVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmVentas
     */
     DefaultTableModel t = new DefaultTableModel();
    Archivo x = new Archivo();

    public void tblGanancias() {
        t.addColumn("MODELO");
        t.addColumn("TOTAL COMPRADOS");
        t.addColumn("COLOR");
        t.addColumn("GANANCIA TOTAL");
        ingresar();
    }
    
    public void ingresar() {
       
        String linea, vector[];
        int fila = 0;
        String precio = null;
        int num=0;
        String mayor=null;
        String arreglo[]={"sail","camaro","venue","elantra","rush","corolla"};
        String colores[]={"plateado","rojo","azul marino","blanco","vino","turquesa"};
        String color=null;
        double precios[]={0,0,0,0,0,0};
        int sail=0,camaro = 0,venue=0,elantra=0,rush=0,corolla=0;
        try {
            FileReader leer = new FileReader("vehiculos.txt");
            BufferedReader adquirir = new BufferedReader(leer);
            linea = adquirir.readLine();
            while (linea != null) {
                vector = linea.split("#");
                if(vector[1].equalsIgnoreCase("CAMARO"))
                {
                    ++camaro;
                    precios[1]=precios[1]+Double.parseDouble(vector[6]);
                }else
                    if(vector[1].equalsIgnoreCase("SAIL"))
                        {
                    ++sail;
                    precios[0]=precios[1]+Double.parseDouble(vector[6]);
                }else
                        if(vector[1].equalsIgnoreCase("VENUE"))
                            {
                    ++venue;
                    precios[2]=precios[1]+Double.parseDouble(vector[6]);
                }else
                            if(vector[1].equalsIgnoreCase("ELANTRA"))
                                {
                    ++elantra;
                    precios[3]=precios[1]+Double.parseDouble(vector[6]);
                }else
                                if(vector[1].equalsIgnoreCase("RUSH"))
                                    {
                    ++rush;
                    precios[4]=precios[1]+Double.parseDouble(vector[6]);
                }else
                                    if(vector[1].equalsIgnoreCase("COROLLA"))
                                        {
                    ++corolla;
                    precios[5]=precios[1]+Double.parseDouble(vector[6]);
                }
                 linea = adquirir.readLine();                   
            }
            int arreglo2[]={sail,camaro,venue,elantra,rush,corolla};
            for(int i=0;i<arreglo2.length;i++)
            {
                if(arreglo2[i]>num)
                {
                    num=arreglo2[i];
                    mayor=arreglo[i];
                    color=colores[i];
                    precio=String.format("%.3f",precios[i]);
                }
            }
            if(num!=1)
            {
                 t.setNumRows(0);
            t.addRow(new Object[1]);
             t.setValueAt(mayor, 0, 0); 
              t.setValueAt(num, 0, 1);          
            t.setValueAt(color, 0, 2); 
            t.setValueAt(precio, 0, 3);  
            }else System.out.println("NO HAY MAS COMPRADO");
           
        } catch (FileNotFoundException ex) {
            System.err.println("ERROR AL LEER EL ARCHIVO");
        } catch (IOException ex) {
            System.err.println("ERROR AL LEER EL ARCHIVO");
        }
    }
    public frmVentas(java.awt.Frame parent, boolean modal) {
        tblGanancias();
        initComponents();
        this.setTitle("Ventas");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/logoCompra.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ventas");

        jTable1.setModel(t);
        jTable1.setToolTipText("");
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(270, 270, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
